

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


CREATE SCHEMA IF NOT EXISTS `MindIt` DEFAULT CHARACTER SET utf8 ;
USE `MindIt` ;

-- -----------------------------------------------------
-- Table `INVESTIDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MindIt`.`INVESTIDOR` (
  `ID_INVESTIDOR` INT NOT NULL AUTO_INCREMENT,
  `NOME_USUARIO` VARCHAR(80) NOT NULL,
  `TELEFONE` VARCHAR(15) NOT NULL,
  `EMAIL` VARCHAR(60) NOT NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  `DATA_NASCIMENTO` date NOT NULL,
  `CPF` CHAR(19) NOT NULL,
  `EMPRESA_FAVORITA` INT NULL,
  PRIMARY KEY (`ID_INVESTIDOR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table`PLANO_ANUAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MindIt`.`PLANO_ANUAL` (
  `VALOR` DOUBLE(9,2) NOT NULL,
  `DESCRICAO` VARCHAR(80) NOT NULL,
  `TEMPO` VARCHAR(45) NOT NULL,
  `ID_PLANO_ANUAL` INT NOT NULL,
  PRIMARY KEY (`ID_PLANO_ANUAL`))
ENGINE = InnoDB
COMMENT = 'B';


-- -----------------------------------------------------
-- Table`PLANO_MENSAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MindIt`.`PLANO_MENSAL` (
  `VALOR` DOUBLE(9,2) NOT NULL,
  `DESCRICAO` VARCHAR(80) NOT NULL,
  `TEMPO` VARCHAR(45) NOT NULL,
  `ID_PLANO_MENSAL` INT NOT NULL,
  PRIMARY KEY (`ID_PLANO_MENSAL`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table`PLANO_SEMESTRAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MindIt`.`PLANO_SEMESTRAL` (
  `VALOR` DOUBLE(9,2) NOT NULL,
  `DESCRICAO` VARCHAR(80) NOT NULL,
  `TEMPO` VARCHAR(45) NOT NULL,
  `ID_PLANO_SEMESTRAL` INT NOT NULL,
  PRIMARY KEY (`ID_PLANO_SEMESTRAL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table`ASSINATURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MindIt`.`ASSINATURA` (
  `DATA_INICIO` VARCHAR(45) NOT NULL,
  `DATA_FINAL` VARCHAR(45) NOT NULL,
  `STATUS` VARCHAR(45) NOT NULL,
  `COD_ASSINATURA` INT NOT NULL AUTO_INCREMENT,
  `PLANO_ANUAL_ID_PLANO_ANUAL` INT NOT NULL,
  `PLANO_MENSAL_ID_PLANO_MENSAL` INT NOT NULL,
  `PLANO_SEMESTRAL_ID_PLANO_SEMESTRAL` INT NOT NULL,
  PRIMARY KEY (`COD_ASSINATURA`),
  CONSTRAINT `fk_ASSINATURA_PLANO_ANUAL1`
    FOREIGN KEY (`PLANO_ANUAL_ID_PLANO_ANUAL`)
    REFERENCES `MindIt`.`PLANO_ANUAL` (`ID_PLANO_ANUAL`)
     ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ASSINATURA_PLANO_MENSAL1`
    FOREIGN KEY (`PLANO_MENSAL_ID_PLANO_MENSAL`)
    REFERENCES `MindIt`.`PLANO_MENSAL` (`ID_PLANO_MENSAL`)
     ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ASSINATURA_PLANO_SEMESTRAL1`
    FOREIGN KEY (`PLANO_SEMESTRAL_ID_PLANO_SEMESTRAL`)
    REFERENCES `MindIt`.`PLANO_SEMESTRAL` (`ID_PLANO_SEMESTRAL`)
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table`EMPREENDEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MindIt`.`EMPREENDEDOR` (
  `ID_EMPREENDEDOR` INT NOT NULL AUTO_INCREMENT,
  `NOME_USUARIO` VARCHAR(80) NOT NULL,
  `TELEFONE` VARCHAR(15) NOT NULL,
  `DATA_NASCIMENTO` date NOT NULL,
  `EMAIL` VARCHAR(60) NOT NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  `CPF` CHAR(19) NOT NULL,
  `EMPRESA_ID` INT NULL,
  `ASSINATURA_COD_ASSINATURA` INT NOT NULL,
  PRIMARY KEY (`ID_EMPREENDEDOR`),
  CONSTRAINT `fk_EMPREENDEDOR_ASSINATURA1`
    FOREIGN KEY (`ASSINATURA_COD_ASSINATURA`)
    REFERENCES `MindIt`.`ASSINATURA` (`COD_ASSINATURA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table`DIVULGACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MindIt`.`DIVULGACAO` (
  `EMPRESA_ID` INT NOT NULL,
  `VITRINE_NOME` VARCHAR(45) NOT NULL,
  `DATA` DATE NOT NULL,
  `HORA` DATETIME NOT NULL,
  `STATUS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`VITRINE_NOME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table`EMPRESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MindIt`.`EMPRESA` (
  `ID_EMPRESA` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(80) NOT NULL,
  `TELEFONE` VARCHAR(15) NOT NULL,
  `DESCRICAO` VARCHAR(180) NOT NULL,
  `QUANTIDADE_INVESTIMENTO_PEDIDO` DOUBLE(9,2) NOT NULL,
  `TIPO_MERCADO` VARCHAR(45) NOT NULL,
  `EMPRESA_TIPO` VARCHAR(45) NOT NULL,
  `CIDADE` VARCHAR(45) NOT NULL,
  `CNPJ` CHAR(19) NOT NULL,
  `EMPREENDEDOR_ID_EMPREENDEDOR` INT NOT NULL,
  `DIVULGACAO_VITRINE_NOME` VARCHAR(45) NOT NULL,
  `IMAGEM` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_EMPRESA`),
  CONSTRAINT `fk_EMPRESA_EMPREENDEDOR1`
    FOREIGN KEY (`EMPREENDEDOR_ID_EMPREENDEDOR`)
    REFERENCES `MindIt`.`EMPREENDEDOR` (`ID_EMPREENDEDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPRESA_DIVULGACAO1`
    FOREIGN KEY (`DIVULGACAO_VITRINE_NOME`)
    REFERENCES `MindIt`.`DIVULGACAO` (`VITRINE_NOME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table`CHAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MindIt`.`CHAT` (
  `ID_CHAT` INT NOT NULL AUTO_INCREMENT,
  `ID_DESTINATARIO` INT NOT NULL,
  `ID_REMETENTE` INT NOT NULL,
  `MENSAGEM` TEXT NOT NULL,
  `DATE_TIME` DATETIME NOT NULL,
  `INVESTIDOR_ID_INVESTIDOR` INT NOT NULL,
  `EMPREENDEDOR_ID_EMPREENDEDOR` INT NOT NULL,
  PRIMARY KEY (`ID_CHAT`),
  CONSTRAINT `fk_CHAT_INVESTIDOR1`
    FOREIGN KEY (`INVESTIDOR_ID_INVESTIDOR`)
    REFERENCES `mydb`.`INVESTIDOR` (`ID_INVESTIDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHAT_EMPREENDEDOR1`
    FOREIGN KEY (`EMPREENDEDOR_ID_EMPREENDEDOR`)
    REFERENCES `MindIt`.`EMPREENDEDOR` (`ID_EMPREENDEDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
